version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true

        depends_on:
            -   db
        environment:
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY: base64:xirfeiX6VPVmd+mi8h3ZpzKmuNi4Tg1K0heSlNthcjk=
            APP_DEBUG: "true"
            APP_URL: http://localhost
            LOG_CHANNEL: stack
            LOG_LEVEL: debug
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: weatherproductsuggestions
            DB_USERNAME: laravel
            DB_PASSWORD: laravel
            CACHE_DRIVER: file
            SESSION_DRIVER: file
        working_dir: /var/www/html
        #volumes:
        #    - .:/var/www/html
        ports:
            - "8081:80"
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_DATABASE: weatherproductsuggestions
            MYSQL_ROOT_PASSWORD: root_pass
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network


networks:
    app-network:
        driver: bridge

volumes:
    db_data: {}
